<?php

namespace MDW\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RECOVER_PASSWORD_LINKSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RECOVER_PASSWORD_LINKSRepository extends EntityRepository
{
}
