<?php

namespace MDW\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SERVICES_APP_MODULES_TO_SERVICESRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SERVICES_APP_MODULES_TO_SERVICESRepository extends EntityRepository
{
}
