<?php

namespace MDW\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SERVICE_APP_MODULESRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SERVICE_APP_MODULESRepository extends EntityRepository
{

	public function getPhpModule($module){
	
		$em = $this->getManager();
		
		$dql = "select a from MDWDemoBundle:Users a where a.login=:login";
		$query = $em->createQuery($dql);
		$query->setParameter('login', $login);
		$users = $query->getResult();
		
		//$company_id = $users[0]['companyId']->getCompanyId();
		//return $company_id;
		foreach($users as $user)
		{
			$company_id = $user->getCompanyId();
			return $company_id;
		}

		return -1;
	
	}
	
}
