<?php

namespace MDW\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SERVICESRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SERVICESRepository extends EntityRepository
{

	public function getServiceName($id){
	
		$em = $this->getEntityManager();
		
		$dql = "select a from MDWDemoBundle:Services a where a.id=:id";
		$query = $em->createQuery($dql);
		$query->setParameter('id', $id);
		$service_name = $query->getResult();
		
		//$company_id = $users[0]['companyId']->getCompanyId();
		//return $company_id;
		foreach($service_name as $name)
		{
			$name_serv = $name->getName();
			return $name_serv;
		}

		return -1;
	
	}
	
}
