<?php

namespace MDW\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * serviceappmodulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviceappmodulesRepository extends EntityRepository
{
}
