<?php

namespace MDW\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * servicestocompaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class servicestocompaniesRepository extends EntityRepository
{
	/**
	* Devuelve los servicios de la company pasada por param
	*/
	public function getServicesByCompany($company){
	
		$em = $this->getEntityManager();
		
		$dql = "select a from MDWDemoBundle:servicestocompanies a where a.idCompany=:idcompany";		
		
		$query = $em->createQuery($dql);
		$query->setParameter('idcompany', $company);

		$services = $query->getResult();
		
		return $services;
	
	}
	
	
	public function getDescriptionServiceById($id){
	
		$em = $this->getEntityManager();
		
		$dql = "select a from MDWDemoBundle:servicestocompanies a where a.id=:id";		
		
		$query = $em->createQuery($dql);
		$query->setParameter('id', $id);

		$services = $query->getResult();
		
		$ids_services = array(); // creo el array
		
		foreach($services as $service)
		{
			$ids_services[] = $service->getDescription();
			
		}

		//return -1;
		return $ids_services;
	
	}

}
