<?php

namespace Proxies\__CG__\MDW\DemoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Registers extends \MDW\DemoBundle\Entity\Registers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'ip', 'procedencia', 'publisher', 'nombre', 'apellidos', 'cP', 'provincia', 'telefono', 'genero', 'email', 'pais', 'edad', 'fechaLead', 'preg1', 'preg2', 'preg3', 'extra1', 'extra2');
        }

        return array('__isInitialized__', 'id', 'ip', 'procedencia', 'publisher', 'nombre', 'apellidos', 'cP', 'provincia', 'telefono', 'genero', 'email', 'pais', 'edad', 'fechaLead', 'preg1', 'preg2', 'preg3', 'extra1', 'extra2');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Registers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', array($ip));

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', array());

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcedencia($procedencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcedencia', array($procedencia));

        return parent::setProcedencia($procedencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcedencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcedencia', array());

        return parent::getProcedencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublisher($publisher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublisher', array($publisher));

        return parent::setPublisher($publisher);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublisher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublisher', array());

        return parent::getPublisher();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setCP($cP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCP', array($cP));

        return parent::setCP($cP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCP', array());

        return parent::getCP();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', array($provincia));

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', array());

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero($genero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', array($genero));

        return parent::setGenero($genero);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', array());

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', array($pais));

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', array());

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdad($edad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdad', array($edad));

        return parent::setEdad($edad);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdad', array());

        return parent::getEdad();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaLead($fechaLead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaLead', array($fechaLead));

        return parent::setFechaLead($fechaLead);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaLead', array());

        return parent::getFechaLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreg1($preg1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreg1', array($preg1));

        return parent::setPreg1($preg1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreg1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreg1', array());

        return parent::getPreg1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreg2($preg2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreg2', array($preg2));

        return parent::setPreg2($preg2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreg2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreg2', array());

        return parent::getPreg2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreg3($preg3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreg3', array($preg3));

        return parent::setPreg3($preg3);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreg3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreg3', array());

        return parent::getPreg3();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtra1($extra1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtra1', array($extra1));

        return parent::setExtra1($extra1);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtra1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtra1', array());

        return parent::getExtra1();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtra2($extra2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtra2', array($extra2));

        return parent::setExtra2($extra2);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtra2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtra2', array());

        return parent::getExtra2();
    }

}
